name: bmi_calc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/src/resources/imgs/black-bmi.png
    - lib/src/resources/imgs/bmi-with-colors.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/src/resources/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: lib/src/resources/fonts/Montserrat/Montserrat-Bold.ttf
    - family: Open Sans
      fonts:
        - asset: lib/src/resources/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: lib/src/resources/fonts/Open_Sans/OpenSans-Bold.ttf